"""update transaction type enum to money_received money_paid journal

Revision ID: 5673b8d6ed0c
Revises: 27086b39052f
Create Date: 2026-02-02 01:13:28.006227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5673b8d6ed0c"
down_revision: Union[str, None] = "27086b39052f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
