"""added is_resolved field to feedback model

Revision ID: cf38297d2aa3
Revises: 8c838af81fef
Create Date: 2026-02-03 15:44:56.007780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf38297d2aa3'
down_revision: Union[str, None] = '8c838af81fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('is_resolved', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_feedback_is_resolved'), 'feedback', ['is_resolved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_is_resolved'), table_name='feedback')
    op.drop_column('feedback', 'is_resolved')
    # ### end Alembic commands ###

